# Generated by Django 3.0.7 on 2020-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.IntegerField(max_length=20),
        ),
    ]
